#!/bin/bash

echo
echo =============================
echo Deploying Floreano Experiment
echo =============================

cp -f Models/brain_model/floreano.py $HBP/Models/brain_model/
echo Added Brain

cp -f Models/floreano_box $HBP/Models/
echo Inserted Models

cp -f Experiments/floreano $HBP/Experiments/
echo Set Up Experiment

sed -i -e '/floreano/ d' $HBP/Experiments/_rpmbuildfolders.txt
echo "floreano" >> $HBP/Experiments/_rpmbuildfolders.txt
echo Updated Experiment _rpmbuild

cd $HBP/Models
./create-symlinks.sh
cd $HBP/gzweb
./deploy-gzbridge-nrp.sh

cd $HBP/user-scripts
./configure_nrp
