#!/bin/bash

source $HOME/.bashrc

echo ===========================
echo Temporarily Storing Changes
echo ===========================

cd $HBP
mkdir tmp
echo Creating Temporary Folder Complete


cd $HBP/Experiments/
mv floreano $HBP/tmp/
echo Moving Experiment Complete

cd $HBP/Experiments/_rpmbuild
sed -i -e '/floreano/ d' folders.txt
echo Editing _rpmbuild Complete	

cd $HBP/user-scripts/
./update_nrp update all

echo
echo ===========================
echo Restoring Saved Changes
echo ===========================

cd $HBP/Experiments/_rpmbuild
sed -i -e '/floreano/ d' folders.txt
echo "floreano" >> folders.txt
echo Restored _rpmbuild

cd $HBP/tmp/Experiments/
mv floreano $HBP/Experiments/
echo Restored Experiment


